name: Custom Tasmota Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Compatible PlatformIO & SCons
        run: |
          python -m pip install --upgrade pip
          pip install "platformio==6.1.18" "scons==4.7.0"

      - name: Build Tasmota IR Firmware
        run: |
          platformio run -e tasmota

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasmota-custom
          path: .pio/build/tasmota-ir/firmware.bin
