name: Custom Tasmota Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build Custom Firmware
        run: platformio run -e tasmota

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tasmota-custom
          path: .pio/build/tasmota/firmware.bin
